
<?php
include('googleConfig.php');
$ok=false;
//This $_GET["code"] variable value received after user has login into their Google Account redirct to PHP script then this variable value has been received
if(isset($_GET["code"]))
{
    //It will Attempt to exchange a code for an valid authentication token.
    $token = $google_client->fetchAccessTokenWithAuthCode($_GET["code"]);

    //This condition will check there is any error occur during geting authentication token. If there is no any error occur then it will execute if block of code/
    if(!isset($token['error']))
    {
        //Set the access token used for requests
        $google_client->setAccessToken($token['access_token']);
         session_start();
         $ok=true;
        //Store "access_token" value in $_SESSION variable for future use.
        $_SESSION['access_token'] = $token['access_token'];

        $_SESSION['login'] = $token['access_token'];
        //Create Object of Google Service OAuth 2 class
        $google_service = new Google_Service_Oauth2($google_client);

        //Get user profile data from google
        $data = $google_service->userinfo->get();

        //Below you can find Get profile data and store into $_SESSION variable
        if(!empty($data['given_name']))
        {
            $_SESSION['user_first_name'] = $data['given_name'];
        }

        if(!empty($data['family_name']))
        {
            $_SESSION['user_last_name'] = $data['family_name'];
        }

        if(!empty($data['email']))
        {
            $_SESSION['user_email_address'] = $data['email'];
        }
    }
}


?>
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <title>App</title>
    <link rel="shortcat icon" type="image/png" href="/images/logo_mic2.png">
    <link rel="stylesheet" href="/index.css" media="all">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="/navro.css">
</head>
<body>
<input type="checkbox" id="check">
<label for="check">
    <i class='fas fa-grip-lines' id="btn" style='font-size:40px;color: black'></i>
    <i class="fas fa-times" id="cancel"></i>
</label>
<div class="sidebar">
    <header>Optiuni</header>
    <ul>
        <li <?php if($ok==false)session_start(); if(isset($_SESSION['login'])) echo "style=\"display: none\""?>><a href="/login/login"><i class="fas Login" ></i>Login</a></li>
        <?php if(isset($_SESSION['login']))
            echo "<li><a href=\"/login/logout\"><i class=\"fas Despre_noi\"></i>LogOut</a></li>";
        ?>
        <li><a href="/aboutUs/aboutUS"><i class="fas Despre_noi"></i>Despre noi</a></li>
        <li><a href="/QA/QA"><i class="fas Intrebari"></i>Intrebari frecvente</a></li>
        <li><a href="/contactUs/contactUS"><i class="fas Contact"></i>Contact</a></li>
        <li><a href="/home/index"><i class="fas home"></i>Home</a></li>
    </ul>
</div>
<div id="main">
<div class="element_mijloc">
    <h2>Bine ai venit!</h2>
    <p>Scopul nostru este sa va ajutam sa gasiti produsele dorite cat mai rapid si mai usor. Noi te ajutam sa gasesti si sa compari totul intr-un singur loc.</p>
    <div>
        <div class="buton_cautare">
            <form class="cautare" action="/home/cauta" method="get">
                <div class="bloc_cautare">
                    <input type="text" name="cauta" required placeholder=" Cauta produsul dorit..." aria-hidden="true">
                    <button class="fa fa-search" style="border: none;font-size:50px;outline: none;color: black;background-color: transparent;" type="submit" >
                </div>
            </form>
        </div>
    </div>
</div>
<nav class="Optiuni">
    <ul class="nav-menu">
        <li><a href="/produse/produse" >Imbracaminte</a></li>
        <li><a href="/produse/produse">Electocasnice</a></li>
        <li><a href="/produse/produse">Telefoane</a></li>
        <li><a href="/produse/produse">Calculatoare</a></li>
    </ul>
</nav>
<section></section>
<footer class="footer-distributed">
    <div class="footer-left">
        <img src="/images/logo_mic2.png" />
        <h3>Despre<span>CompareIt</span></h3>
        <p class="footer-links">
            <a href="/home/index">Home</a>
            |
            <a href="/aboutUs/aboutUs">Despre noi</a>
            |
            <a href="/contactUs/contactUs">Contact</a>
        </p>
        <p class="footer-company-name">© 2020 CompareIT </p>
    </div>
    <div class="footer-center">
        <div>
            <i class="fa fa-map-marker"></i>
            <p><span>Str. Frunzei nr. 7 , jud Iasi </span>
                Iasi, Pacurari (cod postal) - 400710</p>
        </div>
        <div>
            <i class="fa fa-phone"></i>
            <p>Telefon : </p>
            <p>+04 0770519234</p>
        </div>
        <div>
            <i class="fa fa-envelope"></i>
            <p>Email : </p>
            <p><a href="mailto:birleanurebeca@yahoo.com">support@CompareIt.com</a></p>
        </div>
    </div>
    <div class="footer-right">
        <p class="footer-company-about">
            <span>Despre noi </span>
            Ofrim posibilitaea de a gasi cea mai buna calitate la cel mai bun pret pentru produsul dorit.
        </p>
        <div class="footer-icons">
            <a href="https://www.facebook.com/"><i class="fa fa-facebook"></i></a>
            <a href="https://twitter.com/login?lang=ro"><i class="fa fa-twitter"></i></a>
            <a href="https://www.instagram.com/"><i class="fa fa-instagram"></i></a>
            <a href="https://ro.linkedin.com/"><i class="fa fa-linkedin"></i></a>
        </div>
    </div>
</footer>
</div>
<?php
if(isset($_GET["session_expired"]))
    echo"   <script>
      alert(\"Your session has expired. Please login again!\");
    </script>";

else if(isset($_GET["login_succes"])){
    session_start();
    echo"   <script>
      alert(\"Hello "+ $_SESSION['username']+ " !\");
    </script>";
}
else if(isset($_GET["logout"])){

    echo"   <script>
      alert(\"Logout of account! !\");
    </script>";
}
else if(isset($_GET["cautare_esuata"])){
    echo"   <script>
      alert(\"Cautare esuata !\");
    </script>";
}

?>
<script src="/JS-uri/navro.js"></script>
</body>
</html>
