
<?php

if (isset($_GET['login_succes'])) {
    session_start();
    $_SESSION['login'] = $_GET['user'];
    $_SESSION['loggedin_time'] = time();
    $_SESSION['username'] = $_GET['user'];
    $_SESSION['id'] = $_GET['id'];
    $ok=true;
}

?>
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>CompareIt</title>
    <link rel="shortcat icon" type="image/png" href="/images/logo_mic2.png">
    <link rel="stylesheet" href="/index.css" media="all">
      <link rel="stylesheet" href="/css/nav-bar.css" media="all">
      <link rel="stylesheet" href="/css/footer.css" media="all">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
  </head>
  <body>

  <div class="element_mijloc">
      <h2>Bine ati venit!</h2>
      <div class="buton_cautare">
          <form class="cautare" action="/home/cauta" method="get">
              <input type="text" name="cauta"  required placeholder="&nbsp Cauta produsul dorit..." aria-hidden="true">
              <button  class="fa fa-search" style="font-size:50px;color: black;border: none; background: transparent;" type="submit"></button>
          </form>
      </div>
      <p>Scopul nostru este acela de a va ajuta sa gasiti produsele dorite cat mai rapid si mai usor. Noi va ajutam sa gasiti si sa comparati totul intr-un singur loc.</p>
  </div>


<?php
include HTMLS.'side-bar.phtml';
include HTMLS.'nav-bar.phtml';
?>



<div id="myModal" class="modal">
  <div class="modal-content">
     <span class="close">&times;</span>
     <p><b>Autentificare: pentru recunoasterea orcarei cereri se va utiliza capul "Session" din Heardes 
      unde se va completa cu id-ul din cont.<br>
       Pentru o cerere necorespunzator formulata:<br>
       Cod: 400<br>
       Raspuns : {<br>
       "Success": "false",<br>
       "Reason": "un motiv specific"<br>
     }<br>
     <br>
     </b></p>

     <p style="color: black;"><b>
     End-Point: localhost:801/AddProduct<br></b></p>
     <p><b>
     HTTP verb: POST<br>
     Body:<br>
     exemplu:<br>
     {<br>
      "category" :"o_categorie",<br>
      "title" : "un titlu3",<br>
      "link": "un_link3",<br>
      "img_link" :"link_imagine3",<br>
      "source" : "site-ul-meu3",<br>
      "details" : {<br>
        "nume1":"valoare13"<br>
       },<br>
      "price": 100<br>
    }<br>
    Raspuns :<br>
    Cod:200<br>
    cand inserarea s-a realizat cu succes<br>
    {<br>
      "Success": "true",<br>
      "Product ID": 1008<br>
    }<br>
    <br>
    </b></p>

    <p style="color: black;"><b>
    End-Point :localhost:801/UpdatePrice<br></b></p>
    <p><b>
    HTTP verb: PUT<br>
    Body:<br>
    exemplu:<br>
    {<br>
      "id":1007,<br>
      "new_price":200<br>
    }<br>
    Raspuns :<br>
    Cod:200<br>
    cand update-ul s-a realizat cu succes<br>
    {<br>
      "Success": "true"<br>
    }<br>
    <br>
    </b></p>

    <p style="color: black;"><b>
    End-Ponit : localhost:801/DeleteProduct?id=id-ul_produsului<br></b></p>
    <p><b>
    HTTP verb: DELETE<br>
    Raspuns :<br>
    Cod:200<br>
    cand stergerea s-a realizat cu succes<br>
    {<br>
      "Success": "true"<br>
    }<br>
    <br>
    </b></p>

    <p style="color: black;"><b>
    End-Point:localhost:801/GetMyProducts<br></b></p>
    <p><b>
    HTTP verb :GET<br>
    Raspuns:<br>
    Cod:200<br>
    {<br>
      "message": "success",<br>
      "products": [<br>
      {<br>
        "category": "imbracaminte",<br>
        "title": "un titlu3",<br>
        "link": "un_link3",<br>
        "img_link": "link_imagine3",<br>
        "source": "outside",<br>
        "details": {<br>
        "nume1": "valoare13"<br>
      },<br>
      "price": 200,<br>
      "owner": "dGs0bXJqOTh1bmRlZmluZWQxNTg4NDEzMjE4ODA4Y3c",<br>
      "id": 1007<br>
    },<br>
    ...<br>
    ]<br>
  }</b></p>
  <br>
  <b>
  <?php if(isset($_SESSION['login']))
    echo "<button onclick=\"showMyAPIid()\" class=\"myAPIidBtn\"><b>ID-ul meu de API</b></button> <p id=\"myID\"> </p>";
  ?>
  </b>
  </div>
</div>

<script>
function showMyAPIid() {
  var id = new String(<?php echo"\"". $_SESSION['id']."\"";?>);
  var coloredId = id.fontcolor("black");
  var mesaj = new String("ID-ul tau de API este: " + coloredId);
  document.getElementById("myID").innerHTML = mesaj;
  var afiseazaMesaj = document.getElementById("myID"); 
  if (afiseazaMesaj.style.display === "none") {
    afiseazaMesaj.style.display = "block";
  } else {
    afiseazaMesaj.style.display = "none";
  }
}
</script>


<script>
// Get the modal
var modal = document.getElementById("myModal");
// Get the button that opens the modal
var btn = document.getElementById("myBtn");
// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];
// When the user clicks the button, open the modal 
btn.onclick = function() {
  modal.style.display = "block";
}
// When the user clicks on <span> (x), close the modal
span.onclick = function() {
  modal.style.display = "none";
}
// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
  if (event.target == modal) {
    modal.style.display = "none";
  }
}
</script>



 <section></section>


    <footer class="footer-distributed">
 
      <div class="footer-left">
          <img src="/images/logo_mic2.png" alt="Logoul firmei noastre CompareIt">
        <h3>Despre<span>CompareIt</span></h3>
 
        <p class="footer-links">
        <a href="/home/index">Home</a>
        |
        <a href="/aboutUs/aboutUs">Despre noi</a>
        |
        <a href="/contactUs/contactUs">Contact</a>
        </p>
 
        <p class="footer-company-name">© 2020 CompareIT </p>
      </div>
 
      <div class="footer-center">
        <div>
          <i class="fa fa-map-marker"></i>
          <p><span>Str. Frunzei nr. 7 , jud Iasi </span>
           Iasi, Pacurari (cod postal) - 400710</p>
        </div>
 
        <div>
          <i class="fa fa-phone"></i>
           <p>Telefon : </p>
          <p>+04 0770519234</p>
        </div>
        <div>
          <i class="fa fa-envelope"></i>
          <p>Email : </p>
          <p><a href="mailto:birleanurebeca@yahoo.com">support@CompareIt.com</a></p>
        </div>
      </div>
      <div class="footer-right">
        <p class="footer-company-about">
          <span>Despre noi </span>
          Ofrim posibilitaea de a gasi cea mai buna calitate la cel mai bun pret pentru produsul dorit.</p>
          <div class="footer-icons">
            <a href="https://www.facebook.com/"><i class="fa fa-facebook"></i></a>
            <a href="https://twitter.com/login?lang=ro"><i class="fa fa-twitter"></i></a>
            <a href="https://www.instagram.com/"><i class="fa fa-instagram"></i></a>
            <a href="https://ro.linkedin.com/"><i class="fa fa-linkedin"></i></a>
          </div>
      </div>
    </footer>
<?php
if(isset($_GET["session_expired"]))
 echo"   <script>alert(\"Your session has expired. Please login again!\");</script>";

else if(isset($_GET["login_succes"])){
echo"   <script>alert(\"Hello ". $_SESSION['username']." !\");</script>";
}
else if(isset($_GET["logout"])){
  
echo"   <script>alert(\"Logout of account! !\");</script>";
}
else if(isset($_GET["cautare_esuata"])){
  echo"   <script>alert(\"Cautare esuata !\");</script>";
}

?>
<script src="/JS-uri/navro.js"></script>
</body>
</html>
