
<?php

if (isset($_GET['login_succes'])) {
    session_start();
    $_SESSION['login'] = $_GET['user'];
    $_SESSION['loggedin_time'] = time();
    $_SESSION['username'] = $_GET['user'];
    $_SESSION['id'] = $_GET['id'];
    $ok=true;
}

?>
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>CompareIt</title>
    <link rel="shortcat icon" type="image/png" href="/images/logo_mic2.png">
    <link rel="stylesheet" href="/index.css" media="all">
      <link rel="stylesheet" href="/css/nav-bar.css" media="all">
      <link rel="stylesheet" href="/css/footer.css" media="all">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
      <script>
          function register_cookie(){
              let url = new URL('http://localhost:<?php echo PORT_LOCAL_SERVER?>/home/cookie?cookie='+document.cookie);
              const http = new XMLHttpRequest();
              http.open("GET", url, true);
              http.onreadystatechange = function()
              {
                  if(http.readyState === 4) {
                      console.log(http.responseText);
                  }
              }
              http.send(null);
          }
          window.onload=register_cookie;
      </script>
  </head>
  <body>

  <div class="element_mijloc">
      <h2>Bine ati venit!</h2>
      <div class="buton_cautare">
          <form class="cautare" action="/home/cauta" method="get">
              <input type="text" name="cauta"  required placeholder="&nbsp Cauta produsul dorit..." aria-hidden="true">
              <button  class="fa fa-search" style="font-size:50px;color: black;border: none; background: transparent;" type="submit"></button>
          </form>
      </div>
      <p>Scopul nostru este acela de a va ajuta sa gasiti produsele dorite cat mai rapid si mai usor. Noi va ajutam sa gasiti si sa comparati totul intr-un singur loc.</p>
  </div>


<?php
include HTMLS.'side-bar.phtml';
include HTMLS.'nav-bar.phtml';
?>


 <section></section>


    <footer class="footer-distributed">
 
      <div class="footer-left">
          <img src="/images/logo_mic2.png" alt="Logoul firmei noastre CompareIt">
        <h3>Despre<span>CompareIt</span></h3>
 
        <p class="footer-links">
        <a href="/home/index">Home</a>
        |
        <a href="/aboutUs/aboutUs">Despre noi</a>
        |
        <a href="/contactUs/contactUs">Contact</a>
        </p>
 
        <p class="footer-company-name">© 2020 CompareIT </p>
      </div>
 
      <div class="footer-center">
        <div>
          <i class="fa fa-map-marker"></i>
          <p><span>Str. Frunzei nr. 7 , jud Iasi </span>
           Iasi, Pacurari (cod postal) - 400710</p>
        </div>
 
        <div>
          <i class="fa fa-phone"></i>
           <p>Telefon : </p>
          <p>+04 0770519234</p>
        </div>
        <div>
          <i class="fa fa-envelope"></i>
          <p>Email : </p>
          <p><a href="mailto:birleanurebeca@yahoo.com">support@CompareIt.com</a></p>
        </div>
      </div>
      <div class="footer-right">
        <p class="footer-company-about">
          <span>Despre noi </span>
          Ofrim posibilitaea de a gasi cea mai buna calitate la cel mai bun pret pentru produsul dorit.</p>
          <div class="footer-icons">
            <a href="https://www.facebook.com/"><i class="fa fa-facebook"></i></a>
            <a href="https://twitter.com/login?lang=ro"><i class="fa fa-twitter"></i></a>
            <a href="https://www.instagram.com/"><i class="fa fa-instagram"></i></a>
            <a href="https://ro.linkedin.com/"><i class="fa fa-linkedin"></i></a>
          </div>
      </div>
    </footer>
<?php
if(isset($_GET["session_expired"]))
 echo"   <script>alert(\"Your session has expired. Please login again!\");</script>";

else if(isset($_GET["login_succes"])){
echo"   <script>alert(\"Hello ". $_SESSION['username']." !\");</script>";
}
else if(isset($_GET["logout"])){
  
echo"   <script>alert(\"Logout of account! !\");</script>";
}
else if(isset($_GET["cautare_esuata"])){
  echo"   <script>alert(\"Cautare esuata !\");</script>";
}

?>
<script src="/JS-uri/navro.js"></script>

</body>
</html>
