<!DOCTYPE html>
<html lang="ro" dir="ltr">
  <head>
    <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>About Us</title>
      <link rel="stylesheet" href="/aboutUs.css">
      <link rel="shortcat icon" type="image/png" href="/images/logo_mic2.png">
      <link rel="stylesheet" href="/css/nav-bar.css" media="all">
      <link rel="stylesheet" href="/css/footer.css" media="all">
      <link rel="stylesheet" href="/css/side-bar.css" media="all">
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  </head>
  <body>
<?php include HTMLS.'side-bar.phtml';?>

   <div class="aboutus">
    
      
          <h2 class="text-center">Despre noi</h2>
          <p class="text">Site-ul CompareIt <b>NU este un magazin virtual</b> ci un portal pentru comparatii de preturi, modele. Nu vindem produsele listate.
             Nu raspundem pentru produsele comandate de la partenerii nostri.
             Pentru a afla mai multe informatii despre produsele listate, va rugam sa contactati magazinele partenere.</br>
          CompareIt este un sistem de comparare online a preturilor si produselor implementat in scopul de a te ajuta sa alegi cele mai bune si mai ieftine produse cautate. Avand in vedere ca in prezent exista o multitudine de magazine virtuale, cumparaturile online au devenit o adevarata aventura la care insa ne incumetam cu totii.</br>
          Te ajutam sa gasesti pretul cel mai bun din sute de magazine online!</p>
          <div class="img-wrap">
            <img src="/images/balanta.jpg" alt="Imaginea unei balante">
          </div>
    
        </div>


<?php include HTMLS.'nav-bar.phtml';?>



 <section></section>
<?php include  HTMLS.'footer.phtml';
?>

    <script src="./../../../public/JS-uri/navro.js"></script>
</body>
</html>
