
<?php
include('googleConfig.php');
?>
<!DOCTYPE html>
<html lang="ro" dir="ltr">
  <head>
    <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Sign Up</title>
     <link rel="stylesheet" href="/signUp.css" media="all">
      <link rel="stylesheet" href="/css/nav-bar.css" media="all">
      <link rel="stylesheet" href="/css/footer.css" media="all">
      <link rel="stylesheet" href="/css/side-bar.css" media="all">
     <link rel="shortcat icon" type="image/png" href="/images/logo_mic2.png">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src='https://kit.fontawesome.com/a076d05399.js'></script>
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
  </head>

  <body>

  <?php include HTMLS.'side-bar.phtml';?>


  <div class="signupbox">
    <img src="/images/avatar_login.png" class="avatar" alt="Login picture">
   	<h1>Creeaza cont</h1>
    <form action="/signUp/signUp" method="get">
      <p>Nume si Prenume</p>
      <input type="text" name="name"  required class="imputbox" >
      <p>Email</p>
      <input type="email" name="email" required class="imputbox">
      <p>Parola</p>
      <input type="password"  name="password" required class="imputbox" >
      <p><span><input type="checkbox" name="accord" required></span> Sunt de acord cu termenii si conditiile serviciilor.</p>
      <button type="submit" class="signbtn">Creeaza cont</button>
      <hr>
      <p class="or">SAU</p>
    </form>  
    <a href= <?php echo "\"".$google_client->createAuthUrl()."\""?> >
      <button  class="googlebtn">
        <p>Conecteaza-te cu </p>
        <img src="/images/google_logo.png" alt="Google logo">
      </button>
    </a>
    <p>Ai deja un cont? <a href="/login/login"> Intra in cont</a></p>
   </div>


    <?php
    include HTMLS."nav-bar.phtml";
    ?>

 <section></section>

  <?php
  include  HTMLS.'footer.phtml';
  ?>
<script src="./../../../public/JS-uri/navro.js"></script>
</body>
</html>
