
<ul class="filtre">
    <li>
        <button type="button" class="collapsible">Pret</button>

        <div class="content">
            <a href=<?php
            echo "\"/produse/produse?categorie=".$_GET["categorie"]."&sursa=".$_GET["sursa"]."&page=".$_GET['page']."&pret1=0&pret2=100\""
            ?>>
                <label class="container"> 0-100
                    <span class="checkmark"></span>
                </label>
            </a>

            <a href=<?php
            echo "\"/produse/produse?categorie=".$_GET["categorie"]."&sursa=".$_GET["sursa"]."&page=".$_GET['page']."&pret1=100&pret2=500\""
            ?>>
                <label class="container"> 100-500
                    <span class="checkmark"></span>
                </label>
            </a>
            <a href=<?php
            echo "\"/produse/produse?categorie=".$_GET["categorie"]."&sursa=".$_GET["sursa"]."&page=".$_GET['page']."&pret1=500&pret2=1500\""
            ?>>
                <label class="container"> 500-1500
                    <span class="checkmark"></span>
                </label>
            </a>
            <a href=<?php
            echo "\"/produse/produse?categorie=".$_GET["categorie"]."&sursa=".$_GET["sursa"]."&page=".$_GET['page']."&pret1=500&pret2=1500\""
            ?>>
                <label class="container"> 1500-2500
                    <span class="checkmark"></span>
                </label>
            </a>
            <a href=<?php
            echo "\"/produse/produse?categorie=".$_GET["categorie"]."&sursa=".$_GET["sursa"]."&page=".$_GET['page']."&pret1=2500&pret2=5000\""
            ?>>
                <label class="container"> 2500-5000
                    <span class="checkmark"></span>
                </label>
            </a>
            <a href=<?php
            echo "\"/produse/produse?categorie=".$_GET["categorie"]."&sursa=".$_GET["sursa"]."&page=".$_GET['page']."&pret1=5000&pret2=10000\""
            ?>>
                <label class="container"> 5000+
                    <span class="checkmark"></span>
                </label>
            </a>
        </div>
    </li>
    <li>
        <button type="button" class="collapsible">Rating minim</button>
        <div class="content">
            <a href=<?php
            echo "\"/produse/produse?categorie=".$_GET["categorie"]."&sursa=".$_GET["sursa"]."&page=".$_GET['page']."&rating_minim=5\""
            ?>>
                <label for="5">5 stele</label><br>
            </a>
            <a href=<?php
            echo "\"/produse/produse?categorie=".$_GET["categorie"]."&sursa=".$_GET["sursa"]."&page=".$_GET['page']."&rating_minim=4\""
            ?>>
                <label for="4">4 stele</label><br>
            </a>
            <a href=<?php
            echo "\"/produse/produse?categorie=".$_GET["categorie"]."&sursa=".$_GET["sursa"]."&page=".$_GET['page']."&rating_minim=3\""
            ?>>
                <label for="3">3 stele</label><br>
            </a>
            <a href=<?php
            echo "\"/produse/produse?categorie=".$_GET["categorie"]."&sursa=".$_GET["sursa"]."&page=".$_GET['page']."&rating_minim=2\""
            ?>>
                <label for="2">2 stele</label><br>
            </a>
        </div>
    </li>
</ul>

