

<footer class="footer-distributed">

  <div class="footer-left">
    <img calss="footer-comp-logo" src="/images/logo_mic2.png" alt="Logoul firmei noastre CompareIt">
    <h3>Despre<span>CompareIt</span></h3>

    <p class="footer-links">
      <a href="/home/index">Home</a>
      |
      <a href="/aboutUs/aboutUs">Despre noi</a>
      |
      <a href="/contactUs/contactUs">Contact</a>

    <p class="footer-company-name">© 2020 CompareIT </p>
  </div>

  <div class="footer-center">
    <div>
      <i class="fa fa-map-marker"></i>
      <p><span>Str. Frunzei nr. 7 , jud Iasi </span>
Iasi, Pacurari (cod postal) - 400710</p>
    </div>

    <div>
      <i class="fa fa-phone"></i>
       <p>Telefon : </p>
      <p>+04 0770519234</p>
    </div>
    <div>
      <i class="fa fa-envelope"></i>
      <p>Email : </p>
      <p><a href="mailto:birleanurebeca@yahoo.com">support@CompareIt.com</a></p>
    </div>
  </div>
  <div class="footer-right">
    <p class="footer-company-about">
      <span>Despre noi </span>
Ofrim posibilitaea de a gasi cea mai buna calitate la cel mai bun pret pentru produsul dorit.</p>
      <div class="footer-icons">
        <a href="https://www.facebook.com/"><i class="fa fa-facebook"></i></a>
        <a href="https://twitter.com/login?lang=ro"><i class="fa fa-twitter"></i></a>
        <a href="https://www.instagram.com/"><i class="fa fa-instagram"></i></a>
        <a href="https://ro.linkedin.com/"><i class="fa fa-linkedin"></i></a>
      </div>
  </div>
</footer>