
<nav class="navbar">
<li class=comparaBtn><a href=/produse/compara><b>COMPARA</b></a></li>
  <div class="drop">
    <button class="dropper">Imbracaminte</button>
    <div class="dropwrap">
        <?php if(defined('SURSA1'))
            echo '<a href="/produse/produse?categorie=imbracaminte&sursa='.DB_NAME2.'&page=1">'.SURSA1.'</a>'?>
        <?php if(defined('SURSA2'))
            echo '<a href="#">'.SURSA2.'</a>'?>
    </div>
  </div>
  <div class="drop">
    <button class="dropper">Electrocasnice</button>
    <div class="dropwrap">
        <?php if(defined('SURSA1'))
            echo '<a href="/produse/produse?categorie=electrocasnice&sursa='.DB_NAME2.'&page=1">'.SURSA1.'</a>'?>
        <?php if(defined('SURSA2'))
            echo '<a href="/produse/produse?categorie=electrocasnice&sursa='.DB_NAME3.'&page=1">'.SURSA2.'</a>'?>
    </div>
  </div>
  <div class="drop">
    <button class="dropper">Telefoane</button>
    <div class="dropwrap">
        <?php if(defined('SURSA1'))
            echo '<a href="/produse/produse?categorie=telefoane&sursa='.DB_NAME2.'&page=1">'.SURSA1.'</a>'?>
        <?php if(defined('SURSA2'))
            echo '<a href="/produse/produse?categorie=telefoane&sursa='.DB_NAME3.'&page=1">'.SURSA2.'</a>'?>
    </div>
  </div>
  <div class="drop">
    <button class="dropper">Calculatoare</button>
    <div class="dropwrap">
        <?php if(defined('SURSA1'))
            echo '<a href="/produse/produse?categorie=calculatoare&sursa='.DB_NAME2.'&page=1">'.SURSA1.'</a>'?>
        <?php if(defined('SURSA2'))
            echo '<a href="/produse/produse?categorie=calculatoare&sursa='.DB_NAME3.'&page=1">'.SURSA2.'</a>'?>
    </div>
  </div>
  <div class="drop">
    <button class="docAPIbtn" id="myBtn">Documentatie API</button>
  </div>
</nav>



<div id="myModal" class="modal">
  <div class="modal-content">
     <span class="close">&times;</span>
     <p><b>Autentificare: pentru recunoasterea orcarei cereri se va utiliza capul "Session" din Heardes 
      unde se va completa cu id-ul din cont.<br>
       Pentru o cerere necorespunzator formulata:<br>
       Cod: 400<br>
       Raspuns : {<br>
       "Success": "false",<br>
       "Reason": "un motiv specific"<br>
     }<br>
     <br>
     </b></p>

     <p style="color: black;"><b>
     End-Point: localhost:801/AddProduct<br></b></p>
     <p><b>
     HTTP verb: POST<br>
     Body:<br>
     exemplu:<br>
     {<br>
      "category" :"o_categorie",<br>
      "title" : "un titlu3",<br>
      "link": "un_link3",<br>
      "img_link" :"link_imagine3",<br>
      "source" : "site-ul-meu3",<br>
      "details" : {<br>
        "nume1":"valoare13"<br>
       },<br>
      "price": 100<br>
    }<br>
    Raspuns :<br>
    Cod:200<br>
    cand inserarea s-a realizat cu succes<br>
    {<br>
      "Success": "true",<br>
      "Product ID": 1008<br>
    }<br>
    <br>
    </b></p>

    <p style="color: black;"><b>
    End-Point :localhost:801/UpdatePrice<br></b></p>
    <p><b>
    HTTP verb: PUT<br>
    Body:<br>
    exemplu:<br>
    {<br>
      "id":1007,<br>
      "new_price":200<br>
    }<br>
    Raspuns :<br>
    Cod:200<br>
    cand update-ul s-a realizat cu succes<br>
    {<br>
      "Success": "true"<br>
    }<br>
    <br>
    </b></p>

    <p style="color: black;"><b>
    End-Ponit : localhost:801/DeleteProduct?id=id-ul_produsului<br></b></p>
    <p><b>
    HTTP verb: DELETE<br>
    Raspuns :<br>
    Cod:200<br>
    cand stergerea s-a realizat cu succes<br>
    {<br>
      "Success": "true"<br>
    }<br>
    <br>
    </b></p>

    <p style="color: black;"><b>
    End-Point:localhost:801/GetMyProducts<br></b></p>
    <p><b>
    HTTP verb :GET<br>
    Raspuns:<br>
    Cod:200<br>
    {<br>
      "message": "success",<br>
      "products": [<br>
      {<br>
        "category": "imbracaminte",<br>
        "title": "un titlu3",<br>
        "link": "un_link3",<br>
        "img_link": "link_imagine3",<br>
        "source": "outside",<br>
        "details": {<br>
        "nume1": "valoare13"<br>
      },<br>
      "price": 200,<br>
      "owner": "dGs0bXJqOTh1bmRlZmluZWQxNTg4NDEzMjE4ODA4Y3c",<br>
      "id": 1007<br>
    },<br>
    ...<br>
    ]<br>
  }</b></p>
  <br>
  <b>
  <?php if(isset($_SESSION['login']))
    echo "<button onclick=\"showMyAPIid()\" class=\"myAPIidBtn\"><b>ID-ul meu de API</b></button> <p id=\"myID\"> </p>";
  ?>
  </b>
  </div>
</div>

<script>
function showMyAPIid() {
      let id = new String(<?php echo"\"". $_SESSION['id']."\"";?>);
      let coloredId = id.fontcolor("black");
      document.getElementById("myID").innerHTML = new String("ID-ul tau de API este: " + coloredId);
      let afiseazaMesaj = document.getElementById("myID");
      if (afiseazaMesaj.style.display === "none") {
        afiseazaMesaj.style.display = "block";
      } else {
        afiseazaMesaj.style.display = "none";
      }
}
</script>


<script>
// Get the modal
var modal = document.getElementById("myModal");
// Get the button that opens the modal
var btn = document.getElementById("myBtn");
// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];
// When the user clicks the button, open the modal 
btn.onclick = function() {
  modal.style.display = "block";
}
// When the user clicks on <span> (x), close the modal
span.onclick = function() {
  modal.style.display = "none";
}
// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
  if (event.target == modal) {
    modal.style.display = "none";
  }
}
</script>