
<nav class="navbar">
  <div class="drop">
    <button class="dropper">Imbracaminte</button>
    <div class="dropwrap">
      <a href="/produse/produse?categorie=imbracaminte&sursa=produse_emag&page=1">Emag</a>
      <a href="/produse/produse?categorie=imbracaminte&sursa=produse_altex&page=1">Altex</a>
    </div>
  </div>
    <?php if(isset($_SESSION['login']))
        echo "<li class=\"comparaBtn\"><a href=\"/produse/compara\"><b>COMPARA</b></a></li>";
    ?>
  <div class="drop">
    <button class="dropper">Electrocasnice</button>
    <div class="dropwrap">
      <a href="/produse/produse?categorie=electrocasnice&sursa=produse_emag&page=1">Emag</a>
      <a href="/produse/produse?categorie=electrocasnice&sursa=produse_altex&page=1">Altex</a>
    </div>
  </div>
  <div class="drop">
    <button class="dropper">Telefoane</button>
    <div class="dropwrap">
      <a href="/produse/produse?categorie=telefoane&sursa=produse_emag&page=1">Emag</a>
      <a href="/produse/produse?categorie=telefoane&sursa=produse_altex&page=1">Altex</a>
    </div>
  </div>
  <div class="drop">
    <button class="dropper">Calculatoare</button>
    <div class="dropwrap">
      <a href="/produse/produse?categorie=calculatoare&sursa=produse_emag&page=1">Emag</a>
      <a href="/produse/produse?categorie=calculatoare&sursa=produse_altex&page=1">Altex</a>
    </div>
  </div>
</nav>