<!DOCTYPE html>
<html lang="ro" dir="ltr">
  <head>
    <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact Us</title>
     <link rel="stylesheet" href="/css/contactUs.css">
    <link rel="shortcat icon" type="image/png" href="/images/logo_mic2.png">
      <link rel="stylesheet" href="/css/nav-bar.css" media="all">
      <link rel="stylesheet" href="/css/footer.css" media="all">
      <link rel="stylesheet" href="/css/side-bar.css" media="all">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">  
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
  </head>
  <body>
<?php include HTMLS.'side-bar.phtml';?>


  <div class="contact-section">
    
       <h1>CONTACTEAZA-NE,</h1>
       <h2>NU EZITA!</h2>
      
       <div class="info"><h3> Helpline: +04 0770519234 <br/>Luni-Vineri <br/> 10:00 - 17:00</h3></div>
      <div ><img src="/images/contactUs.jpg" class="img" alt="Contact us picture"></div>
     
       <form class="contact-form" action="/contactUs/contactUnregister" method="get">
        <input type="text" name="name" class="contact-form-text" placeholder="Scrie: nume">
        <input type="email" name="email" class="contact-form-text" placeholder="Scrie: email">
        <input type="text" name="telephone" class="contact-form-text" placeholder="Scrie: numar telefon">
        <textarea class="contact-form-text" name="text" placeholder="Scrie: mesaj"></textarea>
        <input type="submit" class="contact-form-btn" value="Trimite">
       </form>
      
   </div>



  <?php
  include HTMLS.'nav-bar.phtml';?>


 <section></section>
  <?php include HTMLS.'footer.phtml';
  ?>

  <script src="./../../../public/JS-uri/navro.js"></script>
</body>
</html>