<!DOCTYPE html>
<html lang="ro" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>FAQ</title>
     <link rel="stylesheet" href="/QA.css">
     <link rel="shortcat icon" type="image/png" href="/images/logo_mic2.png">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
  </head>
  <body>

    <input type="checkbox" id="check">
    <label for="check">
        <i onclick="navroll(true)" class='fas fa-grip-lines' id="btn" style='font-size:40px;color: black'></i>
        <i onclick="navroll(false)" class="fas fa-times" id="cancel"></i>
    </label>


    <div class="sidebar">
    <header>Optiuni</header>
  <ul>
  <li <?php session_start();if(isset($_SESSION['login'])) echo "style=\"display: none\""?>><a href="/login/login"><i class="fas Login" ></i>Login</a></li>
    <?php if(isset($_SESSION['login'])) 
       echo "<li><a href=\"/login/logout\"><i class=\"fas Despre_noi\"></i>LogOut</a></li>";
    ?>
    <li><a href="/aboutUs/aboutUS"><i class="fas Despre_noi"></i>Despre noi</a></li>
    <li><a href="/QA/QA"><i class="fas Intrebari"></i>Intrebari frecvente</a></li>
    <li><a href="/contactUs/contactUS"><i class="fas Contact"></i>Contact</a></li>
    <li><a href="/home/index"><i class="fas home"></i>Home</a></li>
  </ul>
   </div> 


   <div class="container">
     <h1 class="text-center">Intrebari frecvente</h1>
     <h3>Cum ma inregistrez pe CompareIt?</h3> 
     <p>Ca sa beneficiezi de toate functiile site-ului CompareIt <strong>(Wishlist, Alerta pret)</strong> este necesar sa iti faci un cont de utilizator.<br />
  In acest sens trebuie sa accesezi <a href="/signUp/signUp" style="color:black" target="_blank">creaza cont.</a> </p>
     <h3>Cum compar produsele?</h3>  
     <p> </p>  
     <h3>Cum achizitionez un anumit produs?</h3>
     <p>CompareIt nu este un magazin online, ci un comparator de preturi.</p>
     <h3>Ce este un comparator?</h3>
     <p>Este o platforma online, unde regasiti produse de la mai multe magazine. 
Aveti posibilitatea de a compara un produs la mai multe magazine la doar cateva click-uri distanta, avand posibilitatea de a alege cea mai buna oferta si de a merge sa cumperi online direct de la magazinul respectiv.<br>
A se intelege faptul ca un comparator nu este un magazin online.
Comparatorul nu vinde, comparatorul doar da posibilitatea de a vizualiza oferta magazinelor prezente pe el si de a va face legatura printr-un singur buton spre magazinul pe care il alegeti pentru cumpararea acelui produs.</p>
      <h3>De ce folosim CompareIt?</h3>
      <p>Probabil multi se intreaba acest lucru. Va aducem la cunostinta cateva lucruri pe care trebuie sa le stiti despre ajutorul oferit de un comparator online de produse.<br>
Produsele magazinelor de calitate pot face diferenta si pot atrage cumparatorii pe magazinul dumneavoastra online, redirectionati de pe platforma noastra, CompareIt.</p>
      <h3>Cum intru in legatura cu echipa CompareIt?</h3>
      <p>Contactati-ne la numarul de telefon (0722) 374 192, un membru al echipei va raspunde cu profesionalism si promptitudine intrebarilor tale sau ne puteti scrie un mesaj direct accesand pagina <a href="/contactUs/contactUS" style="color:black" target="_blank">contact.</a></p>
   </div>
  

<nav class="Optiuni">
      <ul class="nav-menu">
        <?php if(isset($_SESSION['login']))
          echo "<li class=\"comparaBtn\"><a href=\"#\"><b>COMPARA</b></a></li>";
        ?>
        <li><a href="/produse/produse">Imbracaminte</a></li>
        <li><a href="/produse/produse">Electocasnice</a></li>
        <li><a href="/produse/produse">Telefoane</a></li>
        <li><a href="/produse/produse">Calculatoare</a></li>
      </ul>
</nav>

 <section></section>


 <footer class="footer-distributed">
 
  <div class="footer-left">

    <p class="footer-links">
      <img src="/images/logo_mic2.png" alt="Logoul firmei noastre CompareIt">
      <h3>Despre<span>CompareIt</span></h3>

      <p class="footer-links">
      <a href="/home/index">Home</a>
      |
      <a href="/aboutUs/aboutUs">Despre noi</a>
      |
      <a href="/contactUs/contactUs">Contact</a>

    <p class="footer-company-name">© 2020 CompareIT </p>
  </div>

  <div class="footer-center">
    <div>
      <i class="fa fa-map-marker"></i>
      <p><span>Str. Frunzei nr. 7 , jud Iasi </span>
       Iasi, Pacurari (cod postal) - 400710</p>
    </div>

    <div>
      <i class="fa fa-phone"></i>
       <p>Telefon : </p>
      <p>+04 0770519234</p>
    </div>
    <div>
      <i class="fa fa-envelope"></i>
      <p>Email : </p>
      <p><a href="mailto:birleanurebeca@yahoo.com">support@CompareIt.com</a></p>
    </div>
  </div>
  <div class="footer-right">
    <p class="footer-company-about">
      <span>Despre noi </span>
      Ofrim posibilitaea de a gasi cea mai buna calitate la cel mai bun pret pentru produsul dorit.</p>
      <div class="footer-icons">
        <a href="https://www.facebook.com/"><i class="fa fa-facebook"></i></a>
        <a href="https://twitter.com/login?lang=ro"><i class="fa fa-twitter"></i></a>
        <a href="https://www.instagram.com/"><i class="fa fa-instagram"></i></a>
        <a href="https://ro.linkedin.com/"><i class="fa fa-linkedin"></i></a>
      </div>
  </div>
</footer>
    <script src="./../../../public/JS-uri/navro.js"></script>
</body>
</html>