<!DOCTYPE html>
<html lang="ro" dir="ltr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Produse</title>
    <link rel="shortcat icon" type="image/png" href="/images/logo_mic2.png">
    <link rel="stylesheet" href="/css/nav-bar.css" media="all">
    <link rel="stylesheet" href="/css/compara.css">
    <link rel="stylesheet" href="/css/side-bar.css" media="all">
    <link rel="stylesheet" href="/css/footer.css" media="all">
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>

<div id="main">

<?php
  include HTMLS . 'side-bar.phtml';
  include HTMLS . 'nav-bar.phtml';
?>

<table class="criteriiComp">
    <tr>
      <td><h2>Cel mai bun ca: </h2></td>
      <td class="criteriiCompBtn">
        <a href="#" onclick="comparaPret()"><b>PRET</b></a>
      </td>
      <td class="criteriiCompBtn">
        <a href="#" onclick="comparaRating()"><b>RATING</b></a>
      </td>
      <td class="criteriiCompBtn">
        <a class="rssFeed" href="#" onclick="RSS()"><b>RSS Feed</b></a>
      </td>
    </tr>
</table>  

<div id="products" class="grid-container"></div>   

<div id="modalProduse" class="modalProduse">
  <div id="produseSelectate" class="modal-content">
     <span class="inchide">&times;</span>
  </div>
</div>

</div>

<script src="/JS-uri/navro.js"></script>
<script>
  if(true===<?php  if(isset($_SESSION['id'])) echo "true"; else echo "false";?>) {
    id=<?php if(isset( $_SESSION['id']))echo"\"". $_SESSION['id']."\"";else echo "\"-\""?>;
  }
  else {
    id=document.cookie;
  }
</script>
<script src="/JS-uri/afisareProduse.js"></script>
<script src="/JS-uri/stergeProdus.js"></script>

</body>
</html>