<!DOCTYPE html>
<html lang="ro" dir="ltr">
<script>
    function load() {
        let url = new URL('http://localhost:800/produse/incarcaProduse');
        let params = {
            id:<?php session_start();if(isset($_SESSION['id']))echo"\"". $_SESSION['id']."\"";else echo"\"-\""?>
        } ;

        url.search = new URLSearchParams(params).toString();
        const http = new XMLHttpRequest();

        http.open("GET", url, true);
        http.onreadystatechange = function()
        {

            if(http.readyState === 4 && http.status === 200) {
                const myArr = JSON.parse(http.responseText);
                console.log(myArr);
            }
        }

        http.send(null);
    }
    window.onload = load;
</script>
<head>
    <meta charset="utf-8">
    <title>Produse</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/produse.css">

    <link rel="shortcat icon" type="image/png" href="/images/logo_mic2.png">
    <link rel="stylesheet" href="/css/nav-bar.css" media="all">
    <link rel="stylesheet" href="/css/footer.css" media="all">
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>

<body>

    <?php
    include HTMLS . 'side-bar.phtml';
    include HTMLS.'nav-bar.phtml';
    ?>



</div>

<script src="/JS-uri/navro.js"></script>
</body>
</html>