<!DOCTYPE html>
<html lang="ro" dir="ltr">

<head>
  <meta charset="utf-8">
  <title>Produse</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="/produse.css">
 
  <link rel="shortcat icon" type="image/png" href="/images/logo_mic2.png">
    <link rel="stylesheet" href="/css/nav-bar.css" media="all">
    <link rel="stylesheet" href="/css/footer.css" media="all">
    <link rel="stylesheet" href="/css/side-bar.css" media="all">
  <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="/css/pagerouter.css" media="all">
  
</head>

<body>
<div id="main">
<?php
  include HTMLS.'side-bar.phtml';
  include HTMLS.'nav-bar.phtml';
  if(isset($_GET["categorie"]))
      include HTMLS.'filtre.phtml';
  else
  ?>
<br><br><br>
<div class="grid-container">
    <?php
    require_once('core/makeItems.php');
    makeItems();
    ?>
</div>
  <?php
  if(isset($_GET["categorie"]))
  include HTMLS.'pagerouter.phtml';
  echo '<br>';
  include HTMLS.'footer.phtml';
  ?>


</div>
<script src="/JS-uri/Collapse.js"></script>
<script src="/JS-uri/navro.js"></script>
  <script>

      function produs_ales(id_produs,sursa,category){
         function call2(id_produs, id_user,sursa,category)
          {
              let url = new URL('http://localhost:<?php echo PORT_LOCAL_SERVER?>/produse/alegere');
              let params = {
                  category:category,
                  id:id_user,
                  index: id_produs,
                  source:sursa
              };

              url.search = new URLSearchParams(params).toString();
              const http = new XMLHttpRequest();

              http.open("GET", url, true);
              http.onreadystatechange = function () {
                  console.log(http.responseText);
                  if (http.readyState === 4 && http.status === 200) {
                      console.log(http.responseText);
                  }
              }
              http.send(null);
          }
          if(true===<?php  if(isset($_SESSION['id'])) echo "true"; else echo "false";?>) {
              let id_user=<?php if(isset( $_SESSION['id']))echo"\"". $_SESSION['id']."\"";else echo "\"-\""?>;
              call2(id_produs, id_user,sursa,category);
          }
          else
          {
              let id_user=document.cookie;
              call2(id_produs, id_user,sursa,category);
          }
      }
      function eca(a) {
          function call(a,id){
              let img_link="no_link";
              if(document.getElementById(a + ".image")!==null)
                  img_link= document.getElementById(a + ".image").getAttribute("src").trim();

              let url = new URL('http://localhost:<?php echo PORT_LOCAL_SERVER?>/produse/alegereEbay');
              let params = {
                  category:'search',
                  key_word:<?php if(isset($_GET["nume-produs"]))echo"\"". $_GET["nume-produs"]."\"";else echo"\"-\"" ?>,
                  title:document.getElementById(a + ".title").textContent.trim(),
                  source:'Ebay',
                  link:document.getElementById(a + ".link").getAttribute("href").trim(),
                  imglink:img_link,
                  id:id
              } ;

              url.search = new URLSearchParams(params).toString();
              const http = new XMLHttpRequest();

              http.open("GET", url, true);
              http.onreadystatechange = function()
              {
                  if(http.readyState === 4 && http.status === 200) {
                     console.log(http.responseText);
                  }
              }
              http.send(null);
          }
          if(true===<?php  if(isset($_SESSION['id'])) echo "true"; else echo "false";?>) {
              let id=<?php if(isset( $_SESSION['id']))echo"\"". $_SESSION['id']."\"";else echo "\"-\""?>;
              call(a, id);
          }
          else
          {
              let id=document.cookie;
              //console.log(id);
              call(a, id);
          }
      }
  </script>

</body>
</html>