<?php
require_once ('model/produseModel.php');
if(isset($_GET["nume-produs"]) && isset($_GET["nr-produse"]))
{
$produse_returnate=ProduseModel::cautaProdus($_GET["nume-produs"], $_GET["nr-produse"]);

if($produse_returnate==false)
    header("Location:/index.php?cautare_esuata=1");

if (count($produse_returnate) > 0):
?>

<?php foreach ($produse_returnate as $produs): ?>
<div class="itemi">
    <div class="item" id=<?php echo "\"".array_search($produs, $produse_returnate)."\"";?>>
        <div id=<?php echo "\"".array_search($produs, $produse_returnate)."\"";?> class="c">
            <div class="ct">
                <?php if ($produs->photoURL != ""): ?>
                <img class="ci" id=<?php echo "\"".array_search($produs, $produse_returnate).".image\"";?> id=<?php echo "\"".array_search($produs, $produse_returnate).".image\"";?>  src=<?php echo "\"".$produs->photoURL."\""; endif;?>>
            </div>
            <div id=<?php echo "\"".array_search($produs, $produse_returnate).".title\"";?> class="ct">
                <a id=<?php echo "\"".array_search($produs, $produse_returnate).".link\"";?> href=<?php echo "\"" . $produs->detailsURL . "\"" ?>  >
                    <?php echo $produs->title; ?></a>
            </div>
        </div>
        <div class="c cs">
            <?php foreach ($produs->items as $item):
                echo "<p class=\"".array_search($produs, $produse_returnate)."specs\">";
                echo $item;
                echo "</p>";
            endforeach; ?>
        </div>
        <div class="c cp">
            <button class="purchase" style="vertical-align: middle" onclick=<?php echo "\"eca(".array_search($produs, $produse_returnate).")\"";?>><span style="color: #92999f; font-size: 7vh;"><i class="fas fa-cart-plus"></i></span></button>
        </div>
    </div>
</div>
<?php endforeach; ?>
<?php endif; }?>
