<?php
require_once ('model/ProduseModel.php');
if(isset($_GET["nume-produs"]) && isset($_GET["nr-produse"]))
{
$produse_returnate=ProduseModel::cautaProdus($_GET["nume-produs"], $_GET["nr-produse"]);

if($produse_returnate==false){
    include VIEW.'produse/error.phtml';
}

if (count($produse_returnate) > 0):
?>

<?php foreach ($produse_returnate as $produs): ?>
    <div class="item" id=<?php echo "\"".array_search($produs, $produse_returnate)."\"";?>>
        <div id=<?php echo "\"".array_search($produs, $produse_returnate)."\"";?>>
            <div>
                <button style="float: right;" class="compara" type="button" onclick=<?php echo "\"eca(".array_search($produs, $produse_returnate).")\"";?> title="Compara">
                <span class="tooltip">Compara</span>
                <i class="fas fa-check hovtip"></i>
                </button>
                <?php if ($produs->photoURL != ""): ?>
                <img class="img" id=<?php echo "\"".array_search($produs, $produse_returnate).".image\"";?> id=<?php echo "\"".array_search($produs, $produse_returnate).".image\"";?>  src=<?php echo "\"".$produs->photoURL."\""; endif;?>>
            </div>
            <div style="text-align: center" id=<?php echo "\"".array_search($produs, $produse_returnate).".title\"";?>>
                <a id=<?php echo "\"".array_search($produs, $produse_returnate).".link\"";?> href=<?php echo "\"" . $produs->detailsURL . "\"" ?>  >
                    <?php echo $produs->title; ?></a>
            </div>
        </div>
    </div>
<?php endforeach; ?>
<?php endif; }?>
