
<!DOCTYPE html>
<html>
<body>

<h3>Admin page</h3>

<form action="/admin/changePassword">
  <label for="fname">New password:</label><br>
  <input type="text" id="fname" name="new_password" ><br>
  <input type="submit" value="Submit">
</form>
<form action="http://localhost/phpmyadmin/sql.php?server=1&db=<?php echo DB_NAME ?>&table=users&pos=0">
    <input type="submit" value="Go to database" />
</form>
<form action="/admin/allUserMessages">
    <input type="submit" value="See all user messages " />
</form>
<form action="/admin/newUserMessages">
    <input type="submit" value="See all user messages " />
</form>

</body>
</html>
