<!DOCTYPE html>
<html lang="ro" dir="ltr">
  <head>
    <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Sign In</title>
    <link rel="shortcat icon" type="image/png" href="/images/logo_mic2.png">
     <link rel="stylesheet" href="/css/login.css">
      <link rel="stylesheet" href="/css/nav-bar.css" media="all">
      <link rel="stylesheet" href="/css/footer.css" media="all">
      <link rel="stylesheet" href="/css/side-bar.css" media="all">
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
  <body>

  <?php include HTMLS.'side-bar.phtml';
    include HTMLS.'nav-bar.phtml';
    ?>


  <div class="loginbox">
   	<img src="/images/avatar_login.png" class="avatar" alt="Avatar login picture">
   	<h1>Intra in cont</h1>
   	<form action="/login/login" method="get">
   		<p>Email</p>
   		<input type="email" name="email" required placeholder="Scrie: Email">
   		<p>Parola</p>
   		<input type="password" name="password" required placeholder="Scrie: Parola">
   		<input type="submit" name="Intra in cont" class="intraBtn" value="Intra in cont"> 
    </form> 
    <button class="formBtn"><a href="/signUp/signUp">Nu am cont</a></button>
  </div>


 <section></section>

<?php       
include  HTMLS.'footer.phtml';

if(isset($_GET["session_expired"]))
 echo"   <script>
  alert(\"Your session has expired. Please login again!\");
</script>";

if(isset($_GET["login_fail"]))
echo"   <script>
  alert(\"Login fail. Please try again! !\");
</script>";

?>

  <script src="JS-uri/navro.js"></script>
</body>
</html>