
<!DOCTYPE html>
<html lang="ro" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Sign In</title>
    <link rel="shortcat icon" type="image/png" href="/images/logo_mic2.png">
     <link rel="stylesheet" href="/login.css">
    
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
  <body>

    <input type="checkbox" id="check">
    <label for="check">
        <i onclick="navroll(true)" class='fas fa-grip-lines' id="btn" style='font-size:40px;color: black'></i>
        <i onclick="navroll(false)" class="fas fa-times" id="cancel"></i>
    </label>


    <div class="sidebar">
    <header>Optiuni</header>
  <ul>
    <li><a href="/login/login"><i class="fas Login" ></i>Login</a></li>
    <li><a href="/aboutUs/aboutUS"><i class="fas Despre_noi"></i>Despre noi</a></li>
    <li><a href="/QA/QA"><i class="fas Intrebari"></i>Intrebari frecvente</a></li>
    <li><a href="/contactUs/contactUS"><i class="fas Contact"></i>Contact</a></li>
    <li><a href="/home/index"><i class="fas home"></i>Home</a></li>
  </ul>
   </div>
    <nav class="Optiuni">
        <ul class="nav-menu">
            <li><a href="/produse/produse">Imbracaminte</a></li>
            <li><a href="/produse/produse">Electocasnice</a></li>
            <li><a href="/produse/produse">Telefoane</a></li>
            <li><a href="/produse/produse">Calculatoare</a></li>
        </ul>
    </nav>

   <div class="loginbox">
   	<img src="/images/avatar_login.png" class="avatar">
   	<h1>Intra in cont</h1>
   	<form action="/login/login" method="get">
   		<p>Email</p>
   		<input type="email" name="email" required placeholder="Scrie: Email">
   		<p>Parola</p>
   		<input type="password" name="password" required placeholder="Scrie: Parola">
   		<input type="submit" name="" value="Intra in cont">
   		<a href="#">Mi-am uitat parola</a><br>
   		<a href="/signUp/signUp">Nu am cont</a>
   	</form>
   </div>




 <section></section>


 <footer class="footer-distributed">
 
  <div class="footer-left">
    <img src="/images/logo_mic2.png">
    <h3>Despre<span>CompareIt</span></h3>

    <p class="footer-links">
    <a href="/home/index">Home</a>
      
      <a href="/aboutUs">Despre noi</a>
      |
      <a href="/contactUs/contactUs">Contact</a>

    <p class="footer-company-name">© 2020 CompareIT </p>
  </div>

  <div class="footer-center">
    <div>
      <i class="fa fa-map-marker"></i>
      <p><span>Str. Frunzei nr. 7 , jud Iasi </span>
       Iasi, Pacurari (cod postal) - 400710</p>
    </div>

    <div>
      <i class="fa fa-phone"></i>
       <p>Telefon : </p>
      <p>+04 0770519234</p>
    </div>
    <div>
      <i class="fa fa-envelope"></i>
      <p>Email : </p>
      <p><a href="mailto:birleanurebeca@yahoo.com">support@CompareIt.com</a></p>
    </div>
  </div>
  <div class="footer-right">
    <p class="footer-company-about">
      <span>Despre noi </span>
      Ofrim posibilitaea de a gasi cea mai buna calitate la cel mai bun pret pentru produsul dorit.</p>
      <div class="footer-icons">
        <a href="https://www.facebook.com/"><i class="fa fa-facebook"></i></a>
        <a href="https://twitter.com/login?lang=ro"><i class="fa fa-twitter"></i></a>
        <a href="https://www.instagram.com/"><i class="fa fa-instagram"></i></a>
        <a href="https://ro.linkedin.com/"><i class="fa fa-linkedin"></i></a>
      </div>
  </div>
</footer>
<?php
if(isset($_GET["session_expired"]))
 echo"   <script>
  alert(\"Your session has expired. Please login again!\");
</script>";

if(isset($_GET["login_fail"]))
echo"   <script>
  alert(\"Login fail. Please try again! !\");
</script>";

?>
    <script src="JS-uri/navro.js"></script>
</body>
</html>
</html>
